services:
  fittracker-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fittracker-fe
    ports:
      - '8080:80'
    env_file:
      - .env.prod

volumes:
  node_modules:
